[versions]
kotlin = "2.2.20"
ktlint-gradle = "14.0.1"

[libraries]
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ktlint-gradle       = { group = "org.jlleitschuh.gradle", name = "ktlint-gradle",       version.ref = "ktlint-gradle" }

