[versions]
kotlin = "2.2.20"
ktlint-gradle = "14.0.1"
plugin-publish = "1.3.0"

[libraries]
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ktlint-gradle       = { group = "org.jlleitschuh.gradle", name = "ktlint-gradle",       version.ref = "ktlint-gradle" }

[plugins]
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "plugin-publish" }
